using System.Globalization;

namespace HyperVStatusTray;

public enum TextId
{
    LanguageEnglish,
    LanguageSimplifiedChinese,
    LanguageTraditionalChinese,
    TrayTitle,
    ProgramAlreadyRunning,
    ProgramInitFailedLog,
    ProgramInitFailedMessage,
    LogPathLabel,
    Unknown,
    Other,
    ConfigMissing,
    ConfigEmpty,
    ConfigBackupFailed,
    ConfigInvalid,
    BrokerSecurityEmpty,
    PollIntervalRange,
    StartupTimeoutRange,
    SignalLossRange,
    MonitorFailureRange,
    VmCountRange,
    DuplicateVmName,
    VmNameRequired,
    PingTimeoutRange,
    PingAddressRequired,
    HeartbeatNotRequested,
    HeartbeatDegradedUsable,
    HeartbeatMissingComponent,
    HeartbeatUnknownWithCode,
    IndicatorOff,
    IndicatorStarting,
    IndicatorReady,
    IndicatorFault,
    IndicatorUnknown,
    BrokerNoSnapshot,
    BrokerNoActionSnapshot,
    BrokerNoReloadSnapshot,
    BrokerNoStartupPolicySnapshot,
    BrokerNoLanguageSnapshot,
    BrokerMismatchedResponse,
    BrokerRequestFailed,
    BrokerRequestTimedOut,
    ExitLog,
    PollUnhandledLog,
    BrokerConnectionFailure,
    StatusRefreshFailed,
    WaitingStatus,
    CurrentStartupPolicyUnknown,
    ConfigureStartupPolicy,
    ActionStart,
    ActionConnect,
    ActionShutdown,
    ActionTurnOff,
    ActionRestart,
    ActionReset,
    ClearFault,
    ShowDetails,
    RefreshNow,
    OpenHyperVManager,
    EditConfigAsAdmin,
    ReconfigureVmMonitoring,
    ReloadConfig,
    OpenConfigDirectory,
    OpenBrokerLogDirectory,
    LanguageMenu,
    StartWithWindows,
    Exit,
    StartupSettingChangeFailed,
    ConfigReloadedLog,
    ConfigReloadFailedMessage,
    ConfigReloadFailedTitle,
    CannotReconfigureVmMonitoring,
    ConfigureScriptMissing,
    ConfigureScriptExitMessage,
    ReconfigureVmMonitoringFailed,
    VmMonitoringConfigUpdated,
    ReconfigureCancelledLog,
    ConfirmTurnOff,
    ConfirmReset,
    ConfirmDestructiveTitle,
    OperationAccepted,
    StartFailed,
    RestartFailed,
    OperationFailedTitle,
    StartupPolicyUpdated,
    StartupPolicyUpdateFailedTitle,
    CannotOpenVmConnect,
    BrokerSnapshotVmCountInvalid,
    CurrentStartupPolicyFormat,
    StartupPolicyUnknown,
    StartupPolicyDisabled,
    StartupPolicyStartIfRunning,
    StartupPolicyAlwaysStart,
    StartupPolicyWithDelay,
    DetailsStatusLabel,
    DetailsUpdatedAtLabel,
    DetailsTitle,
    CannotOpenFile,
    AdminOpenCancelled,
    CannotOpenAsAdmin,
    ErrorDetailsWritten,
    LanguageUpdated,
    LanguageUpdateFailed,
    DialogAutomaticStartDelay,
    ButtonOk,
    ButtonCancel,
    ConfigureStartupPolicyTitle,
    WaitingFirstQuery,
    NoStateRead,
    StartRequestSent,
    WaitingHyperVReady,
    RestartRequestSent,
    WaitingRestartReady,
    MonitorQueryFailed,
    MonitorApiUnavailable,
    UnknownMonitoringError,
    VmNotFoundReason,
    VmMissingSummary,
    HyperVCriticalFault,
    StartRequestWaitingState,
    RestartFailedOff,
    StartFailedOff,
    FaultLatched,
    PreviousFaultUncleared,
    Saved,
    Off,
    Paused,
    WaitingReady,
    RestartNotStartedReason,
    RestartNotStartedSummary,
    WaitingGuestRestart,
    PingSucceededMs,
    ReadySignalNormal,
    ReadySignalLostFault,
    ReadySignalLostTemporary,
    RunningGuestNotReady,
    UnhandledHyperVState,
    StartupTimeoutReason,
    RestartTimeout,
    StartupTimeout,
    HealthStateLabel,
    HeartbeatLabel,
    PingLabel,
    PingSucceeded,
    PingFailed,
    UptimeLabel,
    CurrentStageLabel,
    VmNamedNotFound,
    UnknownStartupPolicyNotWritable,
    AutomaticStartDelayRequiredWhenEnabled,
    AutomaticStartDelayMustBeZeroOrGreater,
    VirtualMachineNotFound,
    ActiveVmSettingsNotFound,
    HyperVNoModifyResult,
    HyperVModifyFailed,
    HyperVNoOperationResult,
    HyperVRequestStateChangeFailed,
    ShutdownComponentFailed,
    ShutdownComponentMissing,
    HyperVWmiAccessDenied,
    HyperVWmiQueryFailed,
    HyperVMonitoringFailed,
    BrokerUnsupportedCommand,
    ExecuteVmActionMissing,
    VmIndexOutOfRange,
    UnsupportedVmAction,
    ActionExecutedLog,
    SetStartupPolicyMissing,
    UnsupportedVmStartupPolicy,
    AutomaticStartDelayMissing,
    AutomaticStartDelayNegative,
    StartupPolicyUpdatedLog,
    ConfigInvalidShort,
    BrokerConfigReloaded,
    SetLanguageMissing,
    LanguageUpdatedMessage,
    BrokerRequestFailedLog,
    PipeAcceptFailed,
    PipeUnauthorizedClientLog,
    PipeUnauthorizedClient,
    PipeClientRequestTimedOut,
    PipeRequestTimedOut,
    PipeClientDisconnected,
    PipeClientIoInterrupted,
    PipeClientHandlingFailed,
    BrokerHandleRequestFailed,
    ClientUserUnauthorized,
    ClientPathUnauthorized,
    ClientIdentityUnknown,
    ServiceSidResolveFailed,
    ClientPathLookupFallback,
    ServiceControlManagerConnectFailed,
    BrokerServiceStarted,
    BrokerServiceStopped,
    BrokerServiceFatalError,
    ProgramStartedLog
}

public static class AppText
{
    public const AppLanguage DefaultLanguage = AppLanguage.SimplifiedChinese;

    public static readonly AppLanguage[] SupportedLanguages =
    [
        AppLanguage.English,
        AppLanguage.SimplifiedChinese,
        AppLanguage.TraditionalChinese
    ];

    public static AppLanguage Normalize(AppLanguage language) =>
        Enum.IsDefined(language) ? language : DefaultLanguage;

    public static string LanguageName(AppLanguage language) => Get(language, language switch
    {
        AppLanguage.English => TextId.LanguageEnglish,
        AppLanguage.TraditionalChinese => TextId.LanguageTraditionalChinese,
        _ => TextId.LanguageSimplifiedChinese
    });

    public static string Get(AppLanguage language, TextId id)
    {
        language = Normalize(language);
        return language switch
        {
            AppLanguage.English => English(id),
            AppLanguage.TraditionalChinese => TraditionalChinese(id),
            _ => SimplifiedChinese(id)
        };
    }

    public static string Format(AppLanguage language, TextId id, params object?[] args) =>
        string.Format(CultureInfo.CurrentCulture, Get(language, id), args);

    private static string English(TextId id) => id switch
    {
        TextId.LanguageEnglish => "English",
        TextId.LanguageSimplifiedChinese => "简体中文",
        TextId.LanguageTraditionalChinese => "繁體中文",
        TextId.TrayTitle => "Hyper-V Status Indicator",
        TextId.ProgramAlreadyRunning => "Hyper-V Status Indicator is already running. Check the hidden icons area in the system tray.",
        TextId.ProgramInitFailedLog => "Program initialization failed.",
        TextId.ProgramInitFailedMessage => "Program initialization failed:\n\n{0}\n\nLog: {1}",
        TextId.LogPathLabel => "Log",
        TextId.Unknown => "Unknown",
        TextId.Other => "Other",
        TextId.ConfigMissing => "Configuration file does not exist: {0}. Run configure-vms.ps1 first to select the virtual machines to monitor.",
        TextId.ConfigEmpty => "The configuration file is empty.",
        TextId.ConfigBackupFailed => "(backup failed)",
        TextId.ConfigInvalid => "The configuration file is invalid and the default configuration was not restored automatically.\n\nReason: {0}\nBackup: {1}\nRun configure-vms.ps1 to select the virtual machines to monitor again.",
        TextId.BrokerSecurityEmpty => "broker-security.json is empty.",
        TextId.PollIntervalRange => "PollIntervalSeconds must be between 2 and 60.",
        TextId.StartupTimeoutRange => "StartupTimeoutSeconds must be between 30 and 3600.",
        TextId.SignalLossRange => "SignalLossGraceSeconds must be between 0 and 600.",
        TextId.MonitorFailureRange => "MonitorFailureThreshold must be between 1 and 10.",
        TextId.VmCountRange => "VirtualMachines must contain one or two virtual machines. With one VM, the tray shows one dot; with two VMs, the first appears above the second.",
        TextId.DuplicateVmName => "Virtual machines cannot use duplicate Name values.",
        TextId.VmNameRequired => "Every virtual machine must have a Name.",
        TextId.PingTimeoutRange => "PingTimeoutMilliseconds for virtual machine {0} must be between 100 and 10000.",
        TextId.PingAddressRequired => "Virtual machine {0} has Heartbeat disabled, so PingAddress is required.",
        TextId.HeartbeatNotRequested => "Not queried",
        TextId.HeartbeatDegradedUsable => "Degraded (usable)",
        TextId.HeartbeatMissingComponent => "Component not found",
        TextId.HeartbeatUnknownWithCode => "Unknown ({0})",
        TextId.IndicatorOff => "Off",
        TextId.IndicatorStarting => "Starting / not ready",
        TextId.IndicatorReady => "Ready",
        TextId.IndicatorFault => "Fault",
        TextId.IndicatorUnknown => "Monitoring unknown",
        TextId.BrokerNoSnapshot => "The broker did not return a status snapshot.",
        TextId.BrokerNoActionSnapshot => "The broker did not return a status snapshot after the operation.",
        TextId.BrokerNoReloadSnapshot => "The broker did not return a status snapshot after reloading configuration.",
        TextId.BrokerNoStartupPolicySnapshot => "The broker did not return a status snapshot after updating the startup policy.",
        TextId.BrokerNoLanguageSnapshot => "The broker did not return a status snapshot after updating the language.",
        TextId.BrokerMismatchedResponse => "The broker returned a response for a different request.",
        TextId.BrokerRequestFailed => "Broker request failed.",
        TextId.BrokerRequestTimedOut => "Broker request timed out.",
        TextId.ExitLog => "Program exited.",
        TextId.PollUnhandledLog => "Unhandled exception while polling status.",
        TextId.BrokerConnectionFailure => "Cannot connect to or access the HyperVStatusTrayBroker service: {0}",
        TextId.StatusRefreshFailed => "Status refresh failed: {0}",
        TextId.WaitingStatus => "Waiting for status",
        TextId.CurrentStartupPolicyUnknown => "Current automatic startup policy: Unknown",
        TextId.ConfigureStartupPolicy => "Configure VM automatic startup policy",
        TextId.ActionStart => "Start",
        TextId.ActionConnect => "Connect console",
        TextId.ActionShutdown => "Shut down guest",
        TextId.ActionTurnOff => "Force power off...",
        TextId.ActionRestart => "Restart guest",
        TextId.ActionReset => "Force reset...",
        TextId.ClearFault => "Clear latched fault",
        TextId.ShowDetails => "View detailed status",
        TextId.RefreshNow => "Refresh now",
        TextId.OpenHyperVManager => "Open Hyper-V Manager",
        TextId.EditConfigAsAdmin => "Edit configuration as administrator",
        TextId.ReconfigureVmMonitoring => "Reconfigure VM monitoring",
        TextId.ReloadConfig => "Reload configuration",
        TextId.OpenConfigDirectory => "Open configuration folder",
        TextId.OpenBrokerLogDirectory => "Open broker log folder",
        TextId.LanguageMenu => "Language",
        TextId.StartWithWindows => "Start when Windows signs in",
        TextId.Exit => "Exit",
        TextId.StartupSettingChangeFailed => "Unable to change startup setting",
        TextId.ConfigReloadedLog => "Configuration reloaded.",
        TextId.ConfigReloadFailedMessage => "Configuration reload failed. The current configuration was left unchanged.\n\n{0}",
        TextId.ConfigReloadFailedTitle => "Reload configuration failed",
        TextId.CannotReconfigureVmMonitoring => "Unable to reconfigure VM monitoring",
        TextId.ConfigureScriptMissing => "{0} was not found. Confirm that the script exists in the installation folder.",
        TextId.ConfigureScriptExitMessage => "{0} exited with code {1}.\n\nThe current configuration was left unchanged. If the script wrote a new configuration, inspect it and choose \"Reload configuration\" manually.",
        TextId.ReconfigureVmMonitoringFailed => "Reconfigure VM monitoring failed",
        TextId.VmMonitoringConfigUpdated => "VM monitoring configuration updated.",
        TextId.ReconfigureCancelledLog => "Reconfigure VM monitoring was cancelled.",
        TextId.ConfirmTurnOff => "Cut virtual power to {0} now? Unsaved data in the guest will be lost.",
        TextId.ConfirmReset => "Force reset {0}? This is similar to pressing a physical Reset button, and unsaved data will be lost.",
        TextId.ConfirmDestructiveTitle => "Confirm destructive operation",
        TextId.OperationAccepted => "Operation accepted by Hyper-V.",
        TextId.StartFailed => "Start failed",
        TextId.RestartFailed => "Restart failed",
        TextId.OperationFailedTitle => "{0} operation failed",
        TextId.StartupPolicyUpdated => "VM automatic startup policy updated.",
        TextId.StartupPolicyUpdateFailedTitle => "{0} automatic startup policy update failed",
        TextId.CannotOpenVmConnect => "Unable to open virtual machine connection",
        TextId.BrokerSnapshotVmCountInvalid => "The broker returned an incorrect number of virtual machine statuses.",
        TextId.CurrentStartupPolicyFormat => "Current automatic startup policy: {0}",
        TextId.StartupPolicyUnknown => "Unknown",
        TextId.StartupPolicyDisabled => "Do not start automatically",
        TextId.StartupPolicyStartIfRunning => "Start automatically if it was running before",
        TextId.StartupPolicyAlwaysStart => "Always start automatically",
        TextId.StartupPolicyWithDelay => "{0} (delay {1} seconds)",
        TextId.DetailsStatusLabel => "Status",
        TextId.DetailsUpdatedAtLabel => "Updated",
        TextId.DetailsTitle => "Hyper-V virtual machine status",
        TextId.CannotOpenFile => "Unable to open {0}",
        TextId.AdminOpenCancelled => "Opening {0} as administrator was cancelled.",
        TextId.CannotOpenAsAdmin => "Unable to open {0} as administrator",
        TextId.ErrorDetailsWritten => "{0}\n\nDetails were written to: {1}",
        TextId.LanguageUpdated => "Language updated.",
        TextId.LanguageUpdateFailed => "Language update failed",
        TextId.DialogAutomaticStartDelay => "AutomaticStartDelay (seconds)",
        TextId.ButtonOk => "OK",
        TextId.ButtonCancel => "Cancel",
        TextId.ConfigureStartupPolicyTitle => "Configure automatic startup policy - {0}",
        TextId.WaitingFirstQuery => "Waiting for first query",
        TextId.NoStateRead => "No status has been read from Hyper-V.",
        TextId.StartRequestSent => "Start request sent",
        TextId.WaitingHyperVReady => "Waiting for Hyper-V and guest readiness signals.",
        TextId.RestartRequestSent => "Restart request sent",
        TextId.WaitingRestartReady => "Waiting for the guest to enter restart and regain readiness.",
        TextId.MonitorQueryFailed => "This monitoring query failed ({0}/{1}): {2}",
        TextId.MonitorApiUnavailable => "Unable to access monitoring interface",
        TextId.UnknownMonitoringError => "Unknown monitoring error.",
        TextId.VmNotFoundReason => "Virtual machine {0} was not found.",
        TextId.VmMissingSummary => "Virtual machine does not exist",
        TextId.HyperVCriticalFault => "Hyper-V reported a critical fault",
        TextId.StartRequestWaitingState => "Start request sent, waiting for Hyper-V state change",
        TextId.RestartFailedOff => "The virtual machine returned to Off/Saved during restart and did not recover readiness; restart appears to have failed.",
        TextId.StartFailedOff => "The virtual machine returned to Off/Saved before reaching readiness; startup appears to have failed.",
        TextId.FaultLatched => "Fault latched",
        TextId.PreviousFaultUncleared => "The previous fault has not been cleared.",
        TextId.Saved => "Saved",
        TextId.Off => "Off",
        TextId.Paused => "Virtual machine paused",
        TextId.WaitingReady => "{0}, waiting for readiness",
        TextId.RestartNotStartedReason => "Restart request was sent, but the guest did not appear to enter restart for {0}.",
        TextId.RestartNotStartedSummary => "Restart did not start",
        TextId.WaitingGuestRestart => "Waiting for guest to begin restart",
        TextId.PingSucceededMs => "ICMP Ping succeeded ({0} ms)",
        TextId.ReadySignalNormal => "Readiness signal is normal",
        TextId.ReadySignalLostFault => "Readiness signal lost for too long",
        TextId.ReadySignalLostTemporary => "Readiness signal temporarily lost",
        TextId.RunningGuestNotReady => "Hyper-V is running, guest is not ready",
        TextId.UnhandledHyperVState => "Unhandled Hyper-V state: {0}",
        TextId.StartupTimeoutReason => "The virtual machine has not received a Heartbeat/Ping readiness signal for {0}, exceeding the {1} second threshold.",
        TextId.RestartTimeout => "Restart timed out",
        TextId.StartupTimeout => "Startup timed out",
        TextId.HealthStateLabel => "HealthState",
        TextId.HeartbeatLabel => "Heartbeat",
        TextId.PingLabel => "Ping",
        TextId.PingSucceeded => "succeeded",
        TextId.PingFailed => "failed",
        TextId.UptimeLabel => "Uptime",
        TextId.CurrentStageLabel => "Current stage",
        TextId.VmNamedNotFound => "Virtual machine named {0} was not found.",
        TextId.UnknownStartupPolicyNotWritable => "Unknown is not a writable startup policy.",
        TextId.AutomaticStartDelayRequiredWhenEnabled => "AutomaticStartDelay is required when automatic startup is enabled.",
        TextId.AutomaticStartDelayMustBeZeroOrGreater => "AutomaticStartDelay must be zero or greater.",
        TextId.VirtualMachineNotFound => "Virtual machine was not found: {0}.",
        TextId.ActiveVmSettingsNotFound => "The active virtual machine settings were not found.",
        TextId.HyperVNoModifyResult => "Hyper-V did not return a ModifySystemSettings result.",
        TextId.HyperVModifyFailed => "Hyper-V ModifySystemSettings failed. ReturnValue={0}.",
        TextId.HyperVNoOperationResult => "Hyper-V did not return an operation result.",
        TextId.HyperVRequestStateChangeFailed => "Hyper-V RequestStateChange failed. Return code: {0}.",
        TextId.ShutdownComponentFailed => "{0} failed. Return code: {1}. Check the Shutdown integration service.",
        TextId.ShutdownComponentMissing => "The Hyper-V Shutdown integration service was not found; normal guest shutdown/restart cannot be performed.",
        TextId.HyperVWmiAccessDenied => "Access to Hyper-V WMI was denied. Confirm that the HyperVStatusTrayBroker service account belongs to the Hyper-V Administrators group.",
        TextId.HyperVWmiQueryFailed => "Hyper-V WMI query failed: {0} - {1}",
        TextId.HyperVMonitoringFailed => "Hyper-V monitoring failed: {0}",
        TextId.BrokerUnsupportedCommand => "Unsupported broker command.",
        TextId.ExecuteVmActionMissing => "ExecuteVmAction is missing VmIndex or Action.",
        TextId.VmIndexOutOfRange => "VmIndex is out of range.",
        TextId.UnsupportedVmAction => "Unsupported virtual machine operation.",
        TextId.ActionExecutedLog => "{0}: Executed {1}.",
        TextId.SetStartupPolicyMissing => "SetVmStartupPolicy is missing VmIndex or StartupPolicy.",
        TextId.UnsupportedVmStartupPolicy => "Unsupported VM automatic startup policy.",
        TextId.AutomaticStartDelayMissing => "AutomaticStartDelay is missing.",
        TextId.AutomaticStartDelayNegative => "AutomaticStartDelay cannot be less than 0.",
        TextId.StartupPolicyUpdatedLog => "{0}: Updated automatic startup policy to {1}.",
        TextId.ConfigInvalidShort => "Configuration file is invalid: {0}",
        TextId.BrokerConfigReloaded => "Configuration reloaded.",
        TextId.SetLanguageMissing => "SetLanguage is missing Language.",
        TextId.LanguageUpdatedMessage => "Language updated.",
        TextId.BrokerRequestFailedLog => "Broker request failed: {0}",
        TextId.PipeAcceptFailed => "Failed to accept pipe connection.",
        TextId.PipeUnauthorizedClientLog => "Rejected unauthorized pipe client. Client={0}",
        TextId.PipeUnauthorizedClient => "Pipe client is not authorized.",
        TextId.PipeClientRequestTimedOut => "Pipe client request timed out. Client={0}",
        TextId.PipeRequestTimedOut => "Broker request timed out.",
        TextId.PipeClientDisconnected => "Pipe client disconnected before sending a complete request. Client={0}; {1}",
        TextId.PipeClientIoInterrupted => "Pipe client communication was interrupted. Client={0}; {1}",
        TextId.PipeClientHandlingFailed => "Failed to handle pipe client. Client={0}",
        TextId.BrokerHandleRequestFailed => "Broker failed to process the request.",
        TextId.ClientUserUnauthorized => "Pipe client user is not authorized.",
        TextId.ClientPathUnauthorized => "Pipe client program path is not authorized.",
        TextId.ClientIdentityUnknown => "Unable to verify pipe client identity.",
        TextId.ServiceSidResolveFailed => "Unable to resolve service account SID: {0}",
        TextId.ClientPathLookupFallback => "Unable to read pipe client process path; fell back to user SID validation. Client={0}; Error={1}",
        TextId.ServiceControlManagerConnectFailed => "Unable to connect to Windows Service Control Manager. Win32Error={0}.",
        TextId.BrokerServiceStarted => "Broker service started.",
        TextId.BrokerServiceStopped => "Broker service stopped.",
        TextId.BrokerServiceFatalError => "Broker service encountered a fatal error.",
        TextId.ProgramStartedLog => "Program started.",
        _ => id.ToString()
    };

    private static string SimplifiedChinese(TextId id) => id switch
    {
        TextId.LanguageEnglish => "English",
        TextId.LanguageSimplifiedChinese => "简体中文",
        TextId.LanguageTraditionalChinese => "繁體中文",
        TextId.TrayTitle => "Hyper-V 状态指示器",
        TextId.ProgramAlreadyRunning => "Hyper-V 状态指示器已经在运行。请检查系统托盘的隐藏图标区域。",
        TextId.ProgramInitFailedLog => "程序初始化失败。",
        TextId.ProgramInitFailedMessage => "程序初始化失败：\n\n{0}\n\n日志：{1}",
        TextId.LogPathLabel => "日志",
        TextId.Unknown => "未知",
        TextId.Other => "其他",
        TextId.ConfigMissing => "配置文件不存在：{0}。请先运行 configure-vms.ps1 选择要监视的虚拟机。",
        TextId.ConfigEmpty => "配置文件内容为空。",
        TextId.ConfigBackupFailed => "（备份失败）",
        TextId.ConfigInvalid => "配置文件无效，未自动恢复默认配置。\n\n原因：{0}\n备份：{1}\n请运行 configure-vms.ps1 重新选择要监视的虚拟机。",
        TextId.BrokerSecurityEmpty => "broker-security.json 内容为空。",
        TextId.PollIntervalRange => "PollIntervalSeconds 必须在 2 到 60 之间。",
        TextId.StartupTimeoutRange => "StartupTimeoutSeconds 必须在 30 到 3600 之间。",
        TextId.SignalLossRange => "SignalLossGraceSeconds 必须在 0 到 600 之间。",
        TextId.MonitorFailureRange => "MonitorFailureThreshold 必须在 1 到 10 之间。",
        TextId.VmCountRange => "VirtualMachines 必须包含一台或两台虚拟机；一台时托盘显示一个圆点，两台时第一台显示在上方、第二台显示在下方。",
        TextId.DuplicateVmName => "虚拟机不能使用重复的 Name。",
        TextId.VmNameRequired => "每台虚拟机都必须设置 Name。",
        TextId.PingTimeoutRange => "虚拟机 {0} 的 PingTimeoutMilliseconds 必须在 100 到 10000 之间。",
        TextId.PingAddressRequired => "虚拟机 {0} 已禁用 Heartbeat，因此必须配置 PingAddress。",
        TextId.HeartbeatNotRequested => "未查询",
        TextId.HeartbeatDegradedUsable => "Degraded（仍可用）",
        TextId.HeartbeatMissingComponent => "未发现组件",
        TextId.HeartbeatUnknownWithCode => "未知 ({0})",
        TextId.IndicatorOff => "已关闭",
        TextId.IndicatorStarting => "启动中/未就绪",
        TextId.IndicatorReady => "已就绪",
        TextId.IndicatorFault => "故障",
        TextId.IndicatorUnknown => "监控未知",
        TextId.BrokerNoSnapshot => "Broker 没有返回状态快照。",
        TextId.BrokerNoActionSnapshot => "Broker 没有返回操作后的状态快照。",
        TextId.BrokerNoReloadSnapshot => "Broker 没有返回重新加载后的状态快照。",
        TextId.BrokerNoStartupPolicySnapshot => "Broker 没有返回更新后的状态快照。",
        TextId.BrokerNoLanguageSnapshot => "Broker 没有返回更新语言后的状态快照。",
        TextId.BrokerMismatchedResponse => "Broker 返回了不匹配的响应。",
        TextId.BrokerRequestFailed => "Broker 请求失败。",
        TextId.BrokerRequestTimedOut => "Broker 请求超时。",
        TextId.ExitLog => "程序退出。",
        TextId.PollUnhandledLog => "轮询状态时发生未处理异常。",
        TextId.BrokerConnectionFailure => "无法连接或访问 HyperVStatusTrayBroker 服务：{0}",
        TextId.StatusRefreshFailed => "状态刷新失败：{0}",
        TextId.WaitingStatus => "等待状态",
        TextId.CurrentStartupPolicyUnknown => "当前自动启动策略：未知",
        TextId.ConfigureStartupPolicy => "配置虚拟机自动启动策略",
        TextId.ActionStart => "启动",
        TextId.ActionConnect => "连接控制台",
        TextId.ActionShutdown => "正常关机",
        TextId.ActionTurnOff => "强制关闭电源...",
        TextId.ActionRestart => "正常重启",
        TextId.ActionReset => "强制重置...",
        TextId.ClearFault => "清除故障锁存",
        TextId.ShowDetails => "查看详细状态",
        TextId.RefreshNow => "立即刷新",
        TextId.OpenHyperVManager => "打开 Hyper-V 管理器",
        TextId.EditConfigAsAdmin => "以管理员身份编辑配置文件",
        TextId.ReconfigureVmMonitoring => "重新配置 VM 监视",
        TextId.ReloadConfig => "重新加载配置",
        TextId.OpenConfigDirectory => "打开配置目录",
        TextId.OpenBrokerLogDirectory => "打开 Broker 日志目录",
        TextId.LanguageMenu => "语言",
        TextId.StartWithWindows => "随 Windows 登录启动",
        TextId.Exit => "退出",
        TextId.StartupSettingChangeFailed => "无法修改开机启动设置",
        TextId.ConfigReloadedLog => "配置已重新加载。",
        TextId.ConfigReloadFailedMessage => "配置文件重新加载失败，当前配置保持不变。\n\n{0}",
        TextId.ConfigReloadFailedTitle => "重新加载配置失败",
        TextId.CannotReconfigureVmMonitoring => "无法重新配置 VM 监视",
        TextId.ConfigureScriptMissing => "找不到 {0}。请确认程序安装目录中包含该脚本。",
        TextId.ConfigureScriptExitMessage => "{0} 退出代码：{1}\n\n当前配置保持不变；如脚本已写入新配置，请检查后手动选择“重新加载配置”。",
        TextId.ReconfigureVmMonitoringFailed => "重新配置 VM 监视失败",
        TextId.VmMonitoringConfigUpdated => "VM 监视配置已更新。",
        TextId.ReconfigureCancelledLog => "重新配置 VM 监视已取消。",
        TextId.ConfirmTurnOff => "确定立即切断 {0} 的虚拟电源吗？客户机中未保存的数据会丢失。",
        TextId.ConfirmReset => "确定强制重置 {0} 吗？效果类似按下实体计算机的 Reset 键，未保存的数据会丢失。",
        TextId.ConfirmDestructiveTitle => "确认破坏性操作",
        TextId.OperationAccepted => "操作已被 Hyper-V 接受。",
        TextId.StartFailed => "启动失败",
        TextId.RestartFailed => "重启失败",
        TextId.OperationFailedTitle => "{0} 操作失败",
        TextId.StartupPolicyUpdated => "虚拟机自动启动策略已更新。",
        TextId.StartupPolicyUpdateFailedTitle => "{0} 自动启动策略更新失败",
        TextId.CannotOpenVmConnect => "无法打开虚拟机连接",
        TextId.BrokerSnapshotVmCountInvalid => "Broker 返回的虚拟机状态数量不正确。",
        TextId.CurrentStartupPolicyFormat => "当前自动启动策略：{0}",
        TextId.StartupPolicyUnknown => "未知",
        TextId.StartupPolicyDisabled => "不自动启动",
        TextId.StartupPolicyStartIfRunning => "如果之前正在运行则自动启动",
        TextId.StartupPolicyAlwaysStart => "始终自动启动",
        TextId.StartupPolicyWithDelay => "{0}（延迟 {1} 秒）",
        TextId.DetailsStatusLabel => "状态",
        TextId.DetailsUpdatedAtLabel => "更新时间",
        TextId.DetailsTitle => "Hyper-V 虚拟机状态",
        TextId.CannotOpenFile => "无法打开 {0}",
        TextId.AdminOpenCancelled => "以管理员身份打开 {0} 已取消。",
        TextId.CannotOpenAsAdmin => "无法以管理员身份打开 {0}",
        TextId.ErrorDetailsWritten => "{0}\n\n详细信息已写入：{1}",
        TextId.LanguageUpdated => "语言已更新。",
        TextId.LanguageUpdateFailed => "语言更新失败",
        TextId.DialogAutomaticStartDelay => "AutomaticStartDelay（秒）",
        TextId.ButtonOk => "确定",
        TextId.ButtonCancel => "取消",
        TextId.ConfigureStartupPolicyTitle => "配置自动启动策略 - {0}",
        TextId.WaitingFirstQuery => "等待第一次查询",
        TextId.NoStateRead => "尚未从 Hyper-V 读取状态。",
        TextId.StartRequestSent => "启动请求已发送",
        TextId.WaitingHyperVReady => "正在等待 Hyper-V 和客户机就绪信号。",
        TextId.RestartRequestSent => "重启请求已发送",
        TextId.WaitingRestartReady => "正在等待客户机进入重启过程并重新取得就绪信号。",
        TextId.MonitorQueryFailed => "本次监控查询失败（{0}/{1}）：{2}",
        TextId.MonitorApiUnavailable => "无法访问监控接口",
        TextId.UnknownMonitoringError => "未知监控错误。",
        TextId.VmNotFoundReason => "找不到虚拟机 {0}。",
        TextId.VmMissingSummary => "虚拟机不存在",
        TextId.HyperVCriticalFault => "Hyper-V 报告关键故障",
        TextId.StartRequestWaitingState => "启动请求已发送，等待 Hyper-V 状态变化",
        TextId.RestartFailedOff => "虚拟机在重启期间掉回 Off/Saved 且未恢复就绪，疑似重启失败。",
        TextId.StartFailedOff => "虚拟机在达到就绪状态前重新回到 Off/Saved，疑似启动失败。",
        TextId.FaultLatched => "故障已锁存",
        TextId.PreviousFaultUncleared => "先前的故障仍未清除。",
        TextId.Saved => "已保存",
        TextId.Off => "已关闭",
        TextId.Paused => "虚拟机已暂停",
        TextId.WaitingReady => "{0}，等待就绪",
        TextId.RestartNotStartedReason => "重启请求已发送，但持续 {0} 未观察到客户机进入重启过程。",
        TextId.RestartNotStartedSummary => "重启未开始",
        TextId.WaitingGuestRestart => "等待客户机开始重启",
        TextId.PingSucceededMs => "ICMP Ping 成功（{0} ms）",
        TextId.ReadySignalNormal => "就绪信号正常",
        TextId.ReadySignalLostFault => "就绪信号持续丢失",
        TextId.ReadySignalLostTemporary => "就绪信号暂时丢失",
        TextId.RunningGuestNotReady => "Hyper-V 已运行，客户机未就绪",
        TextId.UnhandledHyperVState => "未处理的 Hyper-V 状态：{0}",
        TextId.StartupTimeoutReason => "虚拟机已持续 {0} 未取得 Heartbeat/Ping 就绪信号，超过 {1} 秒阈值。",
        TextId.RestartTimeout => "重启超时",
        TextId.StartupTimeout => "启动超时",
        TextId.HealthStateLabel => "HealthState",
        TextId.HeartbeatLabel => "Heartbeat",
        TextId.PingLabel => "Ping",
        TextId.PingSucceeded => "成功",
        TextId.PingFailed => "失败",
        TextId.UptimeLabel => "Uptime",
        TextId.CurrentStageLabel => "当前阶段",
        TextId.VmNamedNotFound => "找不到名为 {0} 的虚拟机。",
        TextId.UnknownStartupPolicyNotWritable => "Unknown 不是可写的启动策略。",
        TextId.AutomaticStartDelayRequiredWhenEnabled => "启用自动启动时必须提供 AutomaticStartDelay。",
        TextId.AutomaticStartDelayMustBeZeroOrGreater => "AutomaticStartDelay 必须大于或等于 0。",
        TextId.VirtualMachineNotFound => "找不到虚拟机：{0}。",
        TextId.ActiveVmSettingsNotFound => "未找到活动虚拟机设置。",
        TextId.HyperVNoModifyResult => "Hyper-V 没有返回 ModifySystemSettings 结果。",
        TextId.HyperVModifyFailed => "Hyper-V ModifySystemSettings 失败，返回码：{0}。",
        TextId.HyperVNoOperationResult => "Hyper-V 没有返回操作结果。",
        TextId.HyperVRequestStateChangeFailed => "Hyper-V RequestStateChange 失败，返回码：{0}。",
        TextId.ShutdownComponentFailed => "{0} 失败，返回码：{1}。请检查 Shutdown 集成服务。",
        TextId.ShutdownComponentMissing => "未找到 Hyper-V Shutdown 集成服务；无法执行客户机内的正常关机/重启。",
        TextId.HyperVWmiAccessDenied => "访问 Hyper-V WMI 被拒绝。请确认 HyperVStatusTrayBroker 服务账户属于 Hyper-V Administrators 组。",
        TextId.HyperVWmiQueryFailed => "Hyper-V WMI 查询失败：{0} — {1}",
        TextId.HyperVMonitoringFailed => "Hyper-V 监控失败：{0}",
        TextId.BrokerUnsupportedCommand => "不支持的 Broker 命令。",
        TextId.ExecuteVmActionMissing => "ExecuteVmAction 缺少 VmIndex 或 Action。",
        TextId.VmIndexOutOfRange => "VmIndex 不在允许范围内。",
        TextId.UnsupportedVmAction => "不支持的虚拟机操作。",
        TextId.ActionExecutedLog => "{0}: 已执行 {1}。",
        TextId.SetStartupPolicyMissing => "SetVmStartupPolicy 缺少 VmIndex 或 StartupPolicy。",
        TextId.UnsupportedVmStartupPolicy => "不支持的虚拟机自动启动策略。",
        TextId.AutomaticStartDelayMissing => "AutomaticStartDelay 缺失。",
        TextId.AutomaticStartDelayNegative => "AutomaticStartDelay 不能小于 0。",
        TextId.StartupPolicyUpdatedLog => "{0}: 已更新自动启动策略为 {1}。",
        TextId.ConfigInvalidShort => "配置文件无效：{0}",
        TextId.BrokerConfigReloaded => "配置已重新加载。",
        TextId.SetLanguageMissing => "SetLanguage 缺少 Language。",
        TextId.LanguageUpdatedMessage => "语言已更新。",
        TextId.BrokerRequestFailedLog => "Broker 请求失败：{0}",
        TextId.PipeAcceptFailed => "接受 Pipe 连接失败。",
        TextId.PipeUnauthorizedClientLog => "拒绝未授权 Pipe 客户端。Client={0}",
        TextId.PipeUnauthorizedClient => "Pipe 客户端未授权。",
        TextId.PipeClientRequestTimedOut => "Pipe 客户端请求超时。Client={0}",
        TextId.PipeRequestTimedOut => "Broker 请求超时。",
        TextId.PipeClientDisconnected => "Pipe 客户端在发送完整请求前断开。Client={0}; {1}",
        TextId.PipeClientIoInterrupted => "Pipe 客户端通信中断。Client={0}; {1}",
        TextId.PipeClientHandlingFailed => "处理 Pipe 客户端失败。Client={0}",
        TextId.BrokerHandleRequestFailed => "Broker 处理请求失败。",
        TextId.ClientUserUnauthorized => "Pipe 客户端用户未授权。",
        TextId.ClientPathUnauthorized => "Pipe 客户端程序路径未授权。",
        TextId.ClientIdentityUnknown => "无法确认 Pipe 客户端身份。",
        TextId.ServiceSidResolveFailed => "无法解析服务账户 SID：{0}",
        TextId.ClientPathLookupFallback => "无法读取 Pipe 客户端进程路径，已退回到用户 SID 校验。Client={0}; Error={1}",
        TextId.ServiceControlManagerConnectFailed => "无法连接 Windows Service Control Manager，Win32Error={0}。",
        TextId.BrokerServiceStarted => "Broker 服务已启动。",
        TextId.BrokerServiceStopped => "Broker 服务已停止。",
        TextId.BrokerServiceFatalError => "Broker 服务发生致命错误。",
        TextId.ProgramStartedLog => "程序启动。",
        _ => id.ToString()
    };

    private static string TraditionalChinese(TextId id) => id switch
    {
        TextId.LanguageEnglish => "English",
        TextId.LanguageSimplifiedChinese => "简体中文",
        TextId.LanguageTraditionalChinese => "繁體中文",
        TextId.TrayTitle => "Hyper-V 狀態指示器",
        TextId.ProgramAlreadyRunning => "Hyper-V 狀態指示器已經在執行。請檢查系統匣的隱藏圖示區域。",
        TextId.ProgramInitFailedLog => "程式初始化失敗。",
        TextId.ProgramInitFailedMessage => "程式初始化失敗：\n\n{0}\n\n記錄：{1}",
        TextId.LogPathLabel => "記錄",
        TextId.Unknown => "未知",
        TextId.Other => "其他",
        TextId.ConfigMissing => "設定檔不存在：{0}。請先執行 configure-vms.ps1 選擇要監視的虛擬機器。",
        TextId.ConfigEmpty => "設定檔內容為空。",
        TextId.ConfigBackupFailed => "（備份失敗）",
        TextId.ConfigInvalid => "設定檔無效，未自動還原預設設定。\n\n原因：{0}\n備份：{1}\n請執行 configure-vms.ps1 重新選擇要監視的虛擬機器。",
        TextId.BrokerSecurityEmpty => "broker-security.json 內容為空。",
        TextId.PollIntervalRange => "PollIntervalSeconds 必須介於 2 到 60 之間。",
        TextId.StartupTimeoutRange => "StartupTimeoutSeconds 必須介於 30 到 3600 之間。",
        TextId.SignalLossRange => "SignalLossGraceSeconds 必須介於 0 到 600 之間。",
        TextId.MonitorFailureRange => "MonitorFailureThreshold 必須介於 1 到 10 之間。",
        TextId.VmCountRange => "VirtualMachines 必須包含一台或兩台虛擬機器；一台時系統匣顯示一個圓點，兩台時第一台顯示在上方、第二台顯示在下方。",
        TextId.DuplicateVmName => "虛擬機器不能使用重複的 Name。",
        TextId.VmNameRequired => "每台虛擬機器都必須設定 Name。",
        TextId.PingTimeoutRange => "虛擬機器 {0} 的 PingTimeoutMilliseconds 必須介於 100 到 10000 之間。",
        TextId.PingAddressRequired => "虛擬機器 {0} 已停用 Heartbeat，因此必須設定 PingAddress。",
        TextId.HeartbeatNotRequested => "未查詢",
        TextId.HeartbeatDegradedUsable => "Degraded（仍可用）",
        TextId.HeartbeatMissingComponent => "未發現元件",
        TextId.HeartbeatUnknownWithCode => "未知 ({0})",
        TextId.IndicatorOff => "已關閉",
        TextId.IndicatorStarting => "啟動中/未就緒",
        TextId.IndicatorReady => "已就緒",
        TextId.IndicatorFault => "故障",
        TextId.IndicatorUnknown => "監控未知",
        TextId.BrokerNoSnapshot => "Broker 沒有傳回狀態快照。",
        TextId.BrokerNoActionSnapshot => "Broker 沒有傳回操作後的狀態快照。",
        TextId.BrokerNoReloadSnapshot => "Broker 沒有傳回重新載入設定後的狀態快照。",
        TextId.BrokerNoStartupPolicySnapshot => "Broker 沒有傳回更新後的狀態快照。",
        TextId.BrokerNoLanguageSnapshot => "Broker 沒有傳回更新語言後的狀態快照。",
        TextId.BrokerMismatchedResponse => "Broker 傳回了不相符的回應。",
        TextId.BrokerRequestFailed => "Broker 要求失敗。",
        TextId.BrokerRequestTimedOut => "Broker 要求逾時。",
        TextId.ExitLog => "程式結束。",
        TextId.PollUnhandledLog => "輪詢狀態時發生未處理例外。",
        TextId.BrokerConnectionFailure => "無法連線或存取 HyperVStatusTrayBroker 服務：{0}",
        TextId.StatusRefreshFailed => "狀態重新整理失敗：{0}",
        TextId.WaitingStatus => "等待狀態",
        TextId.CurrentStartupPolicyUnknown => "目前自動啟動原則：未知",
        TextId.ConfigureStartupPolicy => "設定虛擬機器自動啟動原則",
        TextId.ActionStart => "啟動",
        TextId.ActionConnect => "連線主控台",
        TextId.ActionShutdown => "正常關機",
        TextId.ActionTurnOff => "強制關閉電源...",
        TextId.ActionRestart => "正常重新啟動",
        TextId.ActionReset => "強制重設...",
        TextId.ClearFault => "清除故障鎖存",
        TextId.ShowDetails => "檢視詳細狀態",
        TextId.RefreshNow => "立即重新整理",
        TextId.OpenHyperVManager => "開啟 Hyper-V 管理員",
        TextId.EditConfigAsAdmin => "以系統管理員身分編輯設定檔",
        TextId.ReconfigureVmMonitoring => "重新設定 VM 監視",
        TextId.ReloadConfig => "重新載入設定",
        TextId.OpenConfigDirectory => "開啟設定目錄",
        TextId.OpenBrokerLogDirectory => "開啟 Broker 記錄目錄",
        TextId.LanguageMenu => "語言",
        TextId.StartWithWindows => "隨 Windows 登入啟動",
        TextId.Exit => "結束",
        TextId.StartupSettingChangeFailed => "無法修改開機啟動設定",
        TextId.ConfigReloadedLog => "設定已重新載入。",
        TextId.ConfigReloadFailedMessage => "設定檔重新載入失敗，目前設定保持不變。\n\n{0}",
        TextId.ConfigReloadFailedTitle => "重新載入設定失敗",
        TextId.CannotReconfigureVmMonitoring => "無法重新設定 VM 監視",
        TextId.ConfigureScriptMissing => "找不到 {0}。請確認程式安裝目錄中包含該指令碼。",
        TextId.ConfigureScriptExitMessage => "{0} 結束代碼：{1}\n\n目前設定保持不變；如指令碼已寫入新設定，請檢查後手動選擇「重新載入設定」。",
        TextId.ReconfigureVmMonitoringFailed => "重新設定 VM 監視失敗",
        TextId.VmMonitoringConfigUpdated => "VM 監視設定已更新。",
        TextId.ReconfigureCancelledLog => "重新設定 VM 監視已取消。",
        TextId.ConfirmTurnOff => "確定立即切斷 {0} 的虛擬電源嗎？客體中未儲存的資料會遺失。",
        TextId.ConfirmReset => "確定強制重設 {0} 嗎？效果類似按下實體電腦的 Reset 鍵，未儲存的資料會遺失。",
        TextId.ConfirmDestructiveTitle => "確認破壞性操作",
        TextId.OperationAccepted => "操作已被 Hyper-V 接受。",
        TextId.StartFailed => "啟動失敗",
        TextId.RestartFailed => "重新啟動失敗",
        TextId.OperationFailedTitle => "{0} 操作失敗",
        TextId.StartupPolicyUpdated => "虛擬機器自動啟動原則已更新。",
        TextId.StartupPolicyUpdateFailedTitle => "{0} 自動啟動原則更新失敗",
        TextId.CannotOpenVmConnect => "無法開啟虛擬機器連線",
        TextId.BrokerSnapshotVmCountInvalid => "Broker 傳回的虛擬機器狀態數量不正確。",
        TextId.CurrentStartupPolicyFormat => "目前自動啟動原則：{0}",
        TextId.StartupPolicyUnknown => "未知",
        TextId.StartupPolicyDisabled => "不自動啟動",
        TextId.StartupPolicyStartIfRunning => "如果之前正在執行則自動啟動",
        TextId.StartupPolicyAlwaysStart => "一律自動啟動",
        TextId.StartupPolicyWithDelay => "{0}（延遲 {1} 秒）",
        TextId.DetailsStatusLabel => "狀態",
        TextId.DetailsUpdatedAtLabel => "更新時間",
        TextId.DetailsTitle => "Hyper-V 虛擬機器狀態",
        TextId.CannotOpenFile => "無法開啟 {0}",
        TextId.AdminOpenCancelled => "以系統管理員身分開啟 {0} 已取消。",
        TextId.CannotOpenAsAdmin => "無法以系統管理員身分開啟 {0}",
        TextId.ErrorDetailsWritten => "{0}\n\n詳細資訊已寫入：{1}",
        TextId.LanguageUpdated => "語言已更新。",
        TextId.LanguageUpdateFailed => "語言更新失敗",
        TextId.DialogAutomaticStartDelay => "AutomaticStartDelay（秒）",
        TextId.ButtonOk => "確定",
        TextId.ButtonCancel => "取消",
        TextId.ConfigureStartupPolicyTitle => "設定自動啟動原則 - {0}",
        TextId.WaitingFirstQuery => "等待第一次查詢",
        TextId.NoStateRead => "尚未從 Hyper-V 讀取狀態。",
        TextId.StartRequestSent => "啟動要求已傳送",
        TextId.WaitingHyperVReady => "正在等待 Hyper-V 和客體就緒訊號。",
        TextId.RestartRequestSent => "重新啟動要求已傳送",
        TextId.WaitingRestartReady => "正在等待客體進入重新啟動流程並重新取得就緒訊號。",
        TextId.MonitorQueryFailed => "本次監控查詢失敗（{0}/{1}）：{2}",
        TextId.MonitorApiUnavailable => "無法存取監控介面",
        TextId.UnknownMonitoringError => "未知監控錯誤。",
        TextId.VmNotFoundReason => "找不到虛擬機器 {0}。",
        TextId.VmMissingSummary => "虛擬機器不存在",
        TextId.HyperVCriticalFault => "Hyper-V 回報關鍵故障",
        TextId.StartRequestWaitingState => "啟動要求已傳送，等待 Hyper-V 狀態變化",
        TextId.RestartFailedOff => "虛擬機器在重新啟動期間掉回 Off/Saved 且未恢復就緒，疑似重新啟動失敗。",
        TextId.StartFailedOff => "虛擬機器在達到就緒狀態前重新回到 Off/Saved，疑似啟動失敗。",
        TextId.FaultLatched => "故障已鎖存",
        TextId.PreviousFaultUncleared => "先前的故障仍未清除。",
        TextId.Saved => "已儲存",
        TextId.Off => "已關閉",
        TextId.Paused => "虛擬機器已暫停",
        TextId.WaitingReady => "{0}，等待就緒",
        TextId.RestartNotStartedReason => "重新啟動要求已傳送，但持續 {0} 未觀察到客體進入重新啟動流程。",
        TextId.RestartNotStartedSummary => "重新啟動未開始",
        TextId.WaitingGuestRestart => "等待客體開始重新啟動",
        TextId.PingSucceededMs => "ICMP Ping 成功（{0} ms）",
        TextId.ReadySignalNormal => "就緒訊號正常",
        TextId.ReadySignalLostFault => "就緒訊號持續遺失",
        TextId.ReadySignalLostTemporary => "就緒訊號暫時遺失",
        TextId.RunningGuestNotReady => "Hyper-V 已執行，客體未就緒",
        TextId.UnhandledHyperVState => "未處理的 Hyper-V 狀態：{0}",
        TextId.StartupTimeoutReason => "虛擬機器已持續 {0} 未取得 Heartbeat/Ping 就緒訊號，超過 {1} 秒閾值。",
        TextId.RestartTimeout => "重新啟動逾時",
        TextId.StartupTimeout => "啟動逾時",
        TextId.HealthStateLabel => "HealthState",
        TextId.HeartbeatLabel => "Heartbeat",
        TextId.PingLabel => "Ping",
        TextId.PingSucceeded => "成功",
        TextId.PingFailed => "失敗",
        TextId.UptimeLabel => "Uptime",
        TextId.CurrentStageLabel => "目前階段",
        TextId.VmNamedNotFound => "找不到名為 {0} 的虛擬機器。",
        TextId.UnknownStartupPolicyNotWritable => "Unknown 不是可寫入的啟動原則。",
        TextId.AutomaticStartDelayRequiredWhenEnabled => "啟用自動啟動時必須提供 AutomaticStartDelay。",
        TextId.AutomaticStartDelayMustBeZeroOrGreater => "AutomaticStartDelay 必須大於或等於 0。",
        TextId.VirtualMachineNotFound => "找不到虛擬機器：{0}。",
        TextId.ActiveVmSettingsNotFound => "未找到作用中的虛擬機器設定。",
        TextId.HyperVNoModifyResult => "Hyper-V 沒有傳回 ModifySystemSettings 結果。",
        TextId.HyperVModifyFailed => "Hyper-V ModifySystemSettings 失敗，傳回碼：{0}。",
        TextId.HyperVNoOperationResult => "Hyper-V 沒有傳回操作結果。",
        TextId.HyperVRequestStateChangeFailed => "Hyper-V RequestStateChange 失敗，傳回碼：{0}。",
        TextId.ShutdownComponentFailed => "{0} 失敗，傳回碼：{1}。請檢查 Shutdown 整合服務。",
        TextId.ShutdownComponentMissing => "未找到 Hyper-V Shutdown 整合服務；無法執行客體內的正常關機/重新啟動。",
        TextId.HyperVWmiAccessDenied => "存取 Hyper-V WMI 被拒絕。請確認 HyperVStatusTrayBroker 服務帳戶屬於 Hyper-V Administrators 群組。",
        TextId.HyperVWmiQueryFailed => "Hyper-V WMI 查詢失敗：{0} — {1}",
        TextId.HyperVMonitoringFailed => "Hyper-V 監控失敗：{0}",
        TextId.BrokerUnsupportedCommand => "不支援的 Broker 命令。",
        TextId.ExecuteVmActionMissing => "ExecuteVmAction 缺少 VmIndex 或 Action。",
        TextId.VmIndexOutOfRange => "VmIndex 不在允許範圍內。",
        TextId.UnsupportedVmAction => "不支援的虛擬機器操作。",
        TextId.ActionExecutedLog => "{0}: 已執行 {1}。",
        TextId.SetStartupPolicyMissing => "SetVmStartupPolicy 缺少 VmIndex 或 StartupPolicy。",
        TextId.UnsupportedVmStartupPolicy => "不支援的虛擬機器自動啟動原則。",
        TextId.AutomaticStartDelayMissing => "AutomaticStartDelay 缺失。",
        TextId.AutomaticStartDelayNegative => "AutomaticStartDelay 不能小於 0。",
        TextId.StartupPolicyUpdatedLog => "{0}: 已更新自動啟動原則為 {1}。",
        TextId.ConfigInvalidShort => "設定檔無效：{0}",
        TextId.BrokerConfigReloaded => "設定已重新載入。",
        TextId.SetLanguageMissing => "SetLanguage 缺少 Language。",
        TextId.LanguageUpdatedMessage => "語言已更新。",
        TextId.BrokerRequestFailedLog => "Broker 要求失敗：{0}",
        TextId.PipeAcceptFailed => "接受 Pipe 連線失敗。",
        TextId.PipeUnauthorizedClientLog => "拒絕未授權 Pipe 用戶端。Client={0}",
        TextId.PipeUnauthorizedClient => "Pipe 用戶端未授權。",
        TextId.PipeClientRequestTimedOut => "Pipe 用戶端要求逾時。Client={0}",
        TextId.PipeRequestTimedOut => "Broker 要求逾時。",
        TextId.PipeClientDisconnected => "Pipe 用戶端在傳送完整要求前中斷。Client={0}; {1}",
        TextId.PipeClientIoInterrupted => "Pipe 用戶端通訊中斷。Client={0}; {1}",
        TextId.PipeClientHandlingFailed => "處理 Pipe 用戶端失敗。Client={0}",
        TextId.BrokerHandleRequestFailed => "Broker 處理要求失敗。",
        TextId.ClientUserUnauthorized => "Pipe 用戶端使用者未授權。",
        TextId.ClientPathUnauthorized => "Pipe 用戶端程式路徑未授權。",
        TextId.ClientIdentityUnknown => "無法確認 Pipe 用戶端身分。",
        TextId.ServiceSidResolveFailed => "無法解析服務帳戶 SID：{0}",
        TextId.ClientPathLookupFallback => "無法讀取 Pipe 用戶端程序路徑，已退回使用者 SID 驗證。Client={0}; Error={1}",
        TextId.ServiceControlManagerConnectFailed => "無法連線 Windows Service Control Manager，Win32Error={0}。",
        TextId.BrokerServiceStarted => "Broker 服務已啟動。",
        TextId.BrokerServiceStopped => "Broker 服務已停止。",
        TextId.BrokerServiceFatalError => "Broker 服務發生嚴重錯誤。",
        TextId.ProgramStartedLog => "程式啟動。",
        _ => id.ToString()
    };
}
